[music]
music_folder = "~/.local/share/.Music/dl"

[yt_dlp]
format = "bestaudio"
noplaylist = true
quiet = true
geo_bypass = true
outtmpl = "%(artist)s - %(title)s"

[lastfm]
username = "polarhive"
mode = "mix"
