#!/bin/sh
# remove any old songs
cd ~/.local/share/.Music/.tmp/dl && rm -f *

# lastfm
username=polarhive
type=recommended

# parse json
response=$(curl -s "https://www.last.fm/player/station/user/${username}/${type}")
id="$(jq -r '.playlist[0].playlinks[0].id' <<< $response)"
a="$(jq -r '.playlist[0].artists[0].name' <<< $response)"
t="$(jq -r '.playlist[0].name' <<< $response)"

# ytdl
yt-dlp "$id" -f 'ba' -x --quiet --ignore-config --restrict-filenames --postprocessor-args "-metadata title='$t' -metadata artist='$a'" || exit

# mpc
name=$(ls)
mv -n ${name} ~/.local/share/.Music/.tmp
mpc -q update
mpc -q add .tmp/${name}
mpc -q play
notify-send "queueing: $t — $a"
