#!/bin/sh
set -e

# config
music_folder="Music"
cd ~/$music_folder/.tmp/dl

# lastfm
username=polarhive
type=mix

# parse json
response=$(curl -s "https://www.last.fm/player/station/user/${username}/${type}")
id="$(jq -r '.playlist[0].playlinks[0].id' <<< $response)"
a="$(jq -r '.playlist[0].artists[0].name' <<< $response)"
t="$(jq -r '.playlist[0].name' <<< $response)"

# ytdl
yt-dlp --postprocessor-args "ffmpeg":"-metadata title='$t' -metadata artist='$a'" -f 'ba' -x --ignore-config -q --progress --restrict-filenames "$id" || exit 1

# mpc
name=$(ls -u | head -1)
mpc -q update
mpc -q add ".tmp/dl/${name}"
mpc -q play

# log
echo "queueing: $t — $a"
notify-send "queueing: $t — $a"
