#!/bin/sh
API_KEY=""
USERNAME="polarhive"

response=$(curl -s "http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=$USERNAME&api_key=$API_KEY&format=json")
current_track=$(echo "$response" | jq -r '.recenttracks.track[0] | if .["@attr"].nowplaying == "true" then .artist["#text"] + " - " + .name else empty end')

if [ -n "$current_track" ]; then
  echo "Currently playing: $current_track"
  echo -n "$current_track" | wl-copy # Copy the track to clipboard
else
  echo "No track is currently playing."
fi
