#!/bin/bash
# skip if empty
set -e
if [ "$(mpc playlist | wc -l)" -eq 0 ]; then
    notify-send "Add songs"
    exit 1
fi

# cleanup
rm -rf ~/.cache/songs; mkdir ~/.cache/songs; cd ~/.cache/songs
rm ~/.local/share/mpd/playlists/songs.m3u; mpc -q save songs
adb shell mkdir -p /sdcard/Music/

# copy to phone
rsync -avL --files-from="$HOME/.local/share/mpd/playlists/songs.m3u" ~/.local/share/.Music "."
adb push ~/.local/share/mpd/playlists/songs.m3u "/sdcard/Music"
adb push ~/.cache/songs/* "/sdcard/Music"
mpc -q clear
